version: '3'
services:
    rabbitmq:
      image: rabbitmq
      environment:
        - DEBUG=true
      volumes:
        - ./data:/var/lib/rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"